#!/bin/bash

# Path to the folder with Dart files
DIR="lib/src/gen/proto"

# Path to the index.dart file
INDEX_FILE="$DIR/index.dart"

# Check if the folder exists
if [ ! -d "$DIR" ]; then
  echo "Directory $DIR does not exist."
  exit 1
fi

# Create/clear the index.dart file
echo "// This file is automatically generated. Do not modify it manually." > "$INDEX_FILE"
echo "" >> "$INDEX_FILE"

# Iterate over all files in the folder and add export lines
for file in "$DIR"/*.dart; do
  if [ -f "$file" ]; then
    file_name=$(basename "$file")
    echo "export '$file_name';" >> "$INDEX_FILE"
  fi
done

echo "index.dart file generated successfully at $INDEX_FILE."