name: trust_wallet_core
description: Trust wallet core package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^13.0.0

ffigen:
  name: TrustWalletCore
  description: Bindings to `gen/headers/**.h
  output:
    bindings: 'lib/src/gen/ffi/generated_bindings.dart'
  headers:
    entry-points:
      - 'gen/headers/**.h'
